function [psth,params,cpsth,tpsth,mpsth] = loadPSTH(folder)
%LOADPSTH   Load a PSTH generated by Xiaojian's in-vivo LSPS rig
%   PSTH = LOADPSTH loads a peristimulus time histogram from the file
%   Par_PSTH.m in the current folder. PSTH is an NxMx32xPxQ matrix where N
%   is the number of bins, M the number of trials, P the number of probes,
%   and Q the number of unique stimulus location and parameter combos. Non
%   32-channel probes are not currently supported.
%
%   PSTH = LOADPSTH(FOLDER) loads it from the folder specified by FOLDER
%   instead.
%
%   [PSTH,PARAMS,CPSTH,TPSTH,MSDF] = LOADPSTH(___) additionally loads the
%   stimulus parameter table PARAMS, the channel-average histogram CPSTH, 
%   the trial-average histogram TPSTH, and the grand average histogram MSDF

%   Written by John Barrett 2018-06-28 16:00 CDT
%   Last updated John Barrett 2018-06-28 16:19 CDT

    if nargin < 1
        folder = pwd;
    end
    
    cd(folder);
    
    if ~exist('./Par_PSTH.mat','file')
        error('There''s no PSTH in this folder.');
    end
    
    load('./Par_PSTH.mat','Par_PSTH');
    
    params = vertcat(Par_PSTH{:,1}); %#ok<NODEF,IDISVAR>
    
    assert(size(params,2) == 4,'I don''t understand the parameters.'); % TODO : 7 column parameters
    
    params = table(params(:,1),params(:,2),params(:,4),params(:,3),'VariableNames',{'PulseWidth','PercentPower','X','Y'});
    
    % TODO : non struct format
    sizes = unique(cell2mat(cellfun(@(p) size(p.PSTH),Par_PSTH(:,2),'UniformOutput',false)),'rows');
    
    assert(min(sizes(:,1) == max(sizes(:,1))),'PSTHs must be the same size apart from number of trials.');
    assert(min(sizes(:,3) == max(sizes(:,3))),'PSTHs must be the same size apart from number of trials.');
    minTrials = min(sizes(:,2));
    
    psth = cell2mat(cellfun(@(p) p.PSTH(:,1:minTrials,:),reshape(Par_PSTH(:,2),1,1,1,size(Par_PSTH,1)),'UniformOutput',false));
    
    psth = reshape(psth,size(psth,1),minTrials,32,[],size(psth,4)); % TODO : non 32-channel probes
    
    if nargout < 3
        return
    end
    
    cpsth = squeeze(mean(psth,3));
    
    if nargout < 4
        return
    end
    
    tpsth = squeeze(mean(psth,2));
    
    if nargout == 5
        mpsth = squeeze(mean(cpsth,2));
    end
end